apps/race/config/routes.rb
Race::Engine.routes.draw do
  root :to => 'rushes#index'
  get 'new-race' => 'rushes#new'
  get 'users' => 'users#index'
  get 'sessions' => 'sessions#index'
  post 'sessions' => 'sessions#create'
  resources :rushes, only: [:index, :new, :create]
  resources :numeric_updates
end

apps/race/app/models/race/numeric_update.rb
module Race
  class NumericUpdate < ActiveRecord::Base

    scope :race_total, ->(race) { where("rush_id = ?", race) }

    belongs_to :rush

    validates_presence_of :quantity
  end
end

apps/race/app/models/race/rush.rb
module Race
  class Rush < ActiveRecord::Base
    has_many :numeric_updates, dependent: :destroy
    validates_presence_of :name
  end
end

apps/race/app/controllers/race/application_controller.rb
module Race
  class ApplicationController < ActionController::Base
  end
end

apps/race/app/controllers/race/main_controller.rb
module Race
  class MainController < ::Race::ApplicationController
    def index
    end
  end
end

apps/race/app/controllers/race/numeric_updates_controller.rb
module Race
  class NumericUpdatesController < ::Race::ApplicationController
    def index
      @updates = NumericUpdate.all
    end

    def new
      @update = NumericUpdate.new
    end

    def create
      @update = NumericUpdate.new(numeric_update_params)
      respond_to do |format|
        if @update.save
          format.html { redirect_to root_path }
        end
      end
    end

  private
    def numeric_update_params
      params.require(:numeric_update).permit(:quantity, :rush_id)
    end
  end
end

apps/race/app/controllers/race/rushes_controller.rb
module Race
  class RushesController < ::Race::ApplicationController
    def index
      @rushes = Rush.all
      @update = NumericUpdate.new
      @updates = NumericUpdate.all
    end

    def index_edit
      @rushes = Rush.all
    end

    def new
      @race = Rush.new
      @update = NumericUpdate.new
    end

    def create
      @race = Rush.new(rushes_params)
      respond_to do |format|
        if @race.save
          format.html { redirect_to root_path }
        end
      end
    end
  private
    def rushes_params
      params.require(:rush).permit(:name, :metric, :description)
    end
  end
end

apps/race/app/controllers/race/sessions_controller.rb
module Race
  class SessionsController < ::Race::ApplicationController
    def index
      #placeholder
    end

    def create
      client = Stormpath::Client.new(
          {
              :api_key => Marabit2::Application.config.storm_path_api_key
          }
      )
      marabit_app = client.applications.search({:name => "Marabit"}).first

      auth_request = Stormpath::Authentication::UsernamePasswordRequest.new params['email'], params['password']
      auth_result = marabit_app.authenticate_account auth_request
      account = auth_result.account
      storm_path_session_id = SecureRandom.uuid
      Rails.cache.write(storm_path_session_id, {full_name: account.full_name})
      session[:storm_path_session_id] = storm_path_session_id
      redirect_to users_url
    end
  end
end

apps/race/app/controllers/race/users_controller.rb
module Race
  class UsersController < ::Race::ApplicationController
    def index
      client = Stormpath::Client.new(
          {
              :api_key => Marabit2::Application.config.storm_path_api_key
          }
      )
      marabit_app = client.applications.search({:name => "Marabit"}).first

      @accounts = marabit_app.accounts
      account = Rails.cache.read(session[:storm_path_session_id])
      @account_name = account[:full_name]
    end
  end
end

apps/race/app/helpers/race/application_helper.rb
module Race
  module ApplicationHelper
  end
end

apps/race/app/helpers/race/rushes_helper.rb
module Race
  module RushesHelper
    def personal_score(user, rush)
      total ||= user.map { |n| if n.rush_id == rush.id; n.quantity end }.compact.reduce(:+)
      metric = rush.metric || ''
      pluralize(total, metric)
    end

    def show_time_status(update)
      unless update == nil
        distance_of_time_in_words(Time.now, update.created_at)
      else
        ''
      end
    end
  end
end

apps/race/app/views/layouts/race/application.slim
doctype html
html
  head
    title Race
    = stylesheet_link_tag 'race/application', media: "all"
    = stylesheet_link_tag 'http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.min.css'
    = javascript_include_tag 'http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js'
    = javascript_include_tag "race/application"
    meta name="viewport" content="initial-scale=1"

    = csrf_meta_tags
  body
    = render 'shared/nav'
    .l-container
      .wrapper
        = yield

apps/race/app/views/race/main/index.html.erb
<h1>back on track!</h1>

apps/race/app/views/race/numeric_updates/index.slim
= @updates.first.quantity

apps/race/app/views/race/numeric_updates/new.slim
.rush-container
  h1.headline New Update
  = simple_form_for(@update) do |f|
    = f.error_notification
    = f.input :quantity
    = f.error :base
    = f.button :submit

apps/race/app/views/race/rushes/_entry.slim
.rush-entry
  .rank-wrapper
    .rank
      h1 1st
    .completed
      h3.current-status content="telephone=no"= personal_score(@updates, rush)
  .details-wrapper
    .title
      h2.headline content="telephone=no"= rush.name
    .links-wrapper
      .action-item.standing-area data-rush='id_#{index}'
        h4.big-link.fa.fa-group
      .action-item.update-area data-rush='id_#{index}'
        h4.big-link.fa.fa-check-circle

apps/race/app/views/race/rushes/_standings.slim
.rush-standings data-content='area' data-rush='#{index}'
  .user
    span.rank.standing-entry 1.
    span.name.standing-entry Me
    span.status.news-line
      = personal_score(@updates, rush)
      ', fix me
      '
      ' ago

    span.total.standing-entry= personal_score(@updates, rush)

apps/race/app/views/race/rushes/_update.slim
.rush-update data-content='area'
  = simple_form_for(@update) do |f|
    = f.input :rush_id, as: :hidden, input_html: { value: rush.id }
    = f.input_field :quantity
    = f.button :submit, 'log'

apps/race/app/views/race/rushes/index.slim
.l-wrapper#rush-container
  - @rushes.each_with_index do |rush, i|
    .rush-wrapper.animated.fadeInDown data-id="rush_#{rush.id}" id="#{rush.id}"
        = render 'entry',     rush: rush, index: i
        = render 'standings', rush: rush, index: i
        = render 'update',    rush: rush, index: i

apps/race/app/views/race/rushes/new.slim
.l-wrapper.animated.fadeInDown.new-race-wrapper
  = simple_form_for(@race) do |f|
    = f.error_notification
    .stage#race-name
      .fa-new-rush.fa.fa-flash.headline.fadeInDown
      h2.headline Start a New Race!
      p.copy
        |
        b' Tip
        '
          Races should take some time to complete. So, make it long enough that it will require discipline and perseverance to win. Like Running 1,500 miles. Or, reading 1,000 pages.
      = f.input_field :name, placeholder: '"Swim 2,000 laps"', autofocus: true
      .status-bar
        .fa.fa-circle
        .fa.fa-circle-o
        .fa.fa-circle-o
        .fa.fa-circle-o
      .wide-btn
        h3.big-link.move-btn
          ' next
          span.fa.fa-chevron-right
    .stage#race-metric
      .fa-new-rush.fa.fa-road.headline.fadeInDown
      h2.headline What's the metric?
      p.copy.center What is the unit of measurement for this race?
      = f.input_field :metric, placeholder: '"mile"'
      .status-bar
        .fa.fa-circle-o
        .fa.fa-circle
        .fa.fa-circle-o
        .fa.fa-circle-o
      .nav-btns
        h3.big-link.back-btn
          span.fa.fa-chevron-left
          ' prev
        h3.big-link.move-btn
          ' next
          span.fa.fa-chevron-right

    .stage#race-desc
      .fa-new-rush.fa.fa-trophy.headline.fadeInDown
      h2.headline What's the prize?
      p.copy.center Every race should have a prize.
      = f.input_field :description, as: :text, placeholder: '"Eternal bragging rights."'
      .status-bar
        .fa.fa-circle-o
        .fa.fa-circle-o
        .fa.fa-circle
        .fa.fa-circle-o
      .nav-btns
        h3.big-link.back-btn
          span.fa.fa-chevron-left
          ' prev
        h3.big-link.move-btn#grab-content
          ' next
          span.fa.fa-chevron-right

    .submit-race#race-review
      .fa-new-rush.fa.fa-flag-checkered.headline.fadeInDown
      h2.headline On your mark.
      = f.error :base
      = f.button :submit, 'Start Race'
      .wide-btn
        h3.big-link.back-btn.simple
          span.fa.fa-chevron-left
          ' prev

apps/race/app/views/race/users/index.slim
| You are logged in as:
- if @account_name
  p

    = @account_name
- else
  i NO ONE


ul
- @accounts.each do |account|
  li
    = account.full_name

apps/race/app/views/shared/_nav.slim
nav#nav
  ul.nav-bar.animated-three.fadeIn
    li.nav-item= link_to rushes_path do
      span.fa.fa-bars
      end
    li.nav-item= link_to new_race_path do
      span.fa.fa-plus-square-o
      end
    li.nav-item= link_to new_race_path do
      span.fa.fa-cog
      end
    li.nav-item= link_to new_race_path do
      span.fa.fa-user
      end